export type UserRole = 
  | 'SUPER_ADMIN'     // 超級管理者
  | 'ADMIN'          // 總管理者
  | 'MANAGER'        // 管理者
  | 'SERVICE_LEADER' // 外場幹部
  | 'BAR_LEADER'    // 內場幹部
  | 'SERVICE'       // 外場人員
  | 'BAR'           // 吧檯人員
  | 'NEW_SERVICE'   // 外場新進人員
  | 'NEW_BAR';      // 吧檯新進人員

export type Permission = 
  | 'VIEW_DASHBOARD'           // 查看主控台
  | 'VIEW_SCHEDULE'           // 查看排班表
  | 'MANAGE_SCHEDULE'         // 管理排班
  | 'VIEW_INVENTORY'         // 查看庫存
  | 'MANAGE_INVENTORY'       // 管理庫存
  | 'VIEW_TRAINING'         // 查看教學內容
  | 'MANAGE_TRAINING'       // 管理教學內容
  | 'VIEW_EVALUATION'       // 查看評優改進
  | 'MANAGE_EVALUATION'     // 管理評優改進
  | 'VIEW_ANNOUNCEMENTS'    // 查看公告
  | 'MANAGE_ANNOUNCEMENTS'  // 管理公告
  | 'VIEW_USERS'           // 查看使用者
  | 'MANAGE_USERS'         // 管理使用者
  | 'VIEW_STATISTICS'      // 查看統計
  | 'MANAGE_SYSTEM'        // 系統設定
  | 'MANAGE_PERMISSIONS';  // 管理權限

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  'SUPER_ADMIN': [
    'VIEW_DASHBOARD', 'VIEW_SCHEDULE', 'MANAGE_SCHEDULE',
    'VIEW_INVENTORY', 'MANAGE_INVENTORY',
    'VIEW_TRAINING', 'MANAGE_TRAINING',
    'VIEW_EVALUATION', 'MANAGE_EVALUATION',
    'VIEW_ANNOUNCEMENTS', 'MANAGE_ANNOUNCEMENTS',
    'VIEW_USERS', 'MANAGE_USERS',
    'VIEW_STATISTICS', 'MANAGE_SYSTEM',
    'MANAGE_PERMISSIONS'
  ],
  'ADMIN': [
    'VIEW_DASHBOARD', 'VIEW_SCHEDULE', 'MANAGE_SCHEDULE',
    'VIEW_INVENTORY', 'MANAGE_INVENTORY',
    'VIEW_TRAINING', 'MANAGE_TRAINING',
    'VIEW_EVALUATION', 'MANAGE_EVALUATION',
    'VIEW_ANNOUNCEMENTS', 'MANAGE_ANNOUNCEMENTS',
    'VIEW_USERS', 'MANAGE_USERS',
    'VIEW_STATISTICS', 'MANAGE_SYSTEM'
  ],
  'MANAGER': [
    'VIEW_DASHBOARD', 'VIEW_SCHEDULE', 'MANAGE_SCHEDULE',
    'VIEW_INVENTORY', 'MANAGE_INVENTORY',
    'VIEW_TRAINING', 'MANAGE_TRAINING',
    'VIEW_EVALUATION', 'MANAGE_EVALUATION',
    'VIEW_ANNOUNCEMENTS', 'MANAGE_ANNOUNCEMENTS',
    'VIEW_USERS', 'MANAGE_USERS',
    'VIEW_STATISTICS'
  ],
  'SERVICE_LEADER': [
    'VIEW_DASHBOARD', 'VIEW_SCHEDULE', 'MANAGE_SCHEDULE',
    'VIEW_INVENTORY', 'MANAGE_INVENTORY',
    'VIEW_TRAINING',
    'VIEW_EVALUATION', 'MANAGE_EVALUATION',
    'VIEW_ANNOUNCEMENTS', 'MANAGE_ANNOUNCEMENTS'
  ],
  'BAR_LEADER': [
    'VIEW_DASHBOARD', 'VIEW_SCHEDULE', 'MANAGE_SCHEDULE',
    'VIEW_INVENTORY', 'MANAGE_INVENTORY',
    'VIEW_TRAINING',
    'VIEW_EVALUATION', 'MANAGE_EVALUATION',
    'VIEW_ANNOUNCEMENTS', 'MANAGE_ANNOUNCEMENTS'
  ],
  'SERVICE': [
    'VIEW_DASHBOARD', 'VIEW_SCHEDULE',
    'VIEW_INVENTORY',
    'VIEW_TRAINING',
    'VIEW_EVALUATION',
    'VIEW_ANNOUNCEMENTS'
  ],
  'BAR': [
    'VIEW_DASHBOARD', 'VIEW_SCHEDULE',
    'VIEW_INVENTORY',
    'VIEW_TRAINING',
    'VIEW_EVALUATION',
    'VIEW_ANNOUNCEMENTS'
  ],
  'NEW_SERVICE': [
    'VIEW_DASHBOARD', 'VIEW_SCHEDULE',
    'VIEW_TRAINING',
    'VIEW_ANNOUNCEMENTS'
  ],
  'NEW_BAR': [
    'VIEW_DASHBOARD', 'VIEW_SCHEDULE',
    'VIEW_TRAINING',
    'VIEW_ANNOUNCEMENTS'
  ]
};